the old project somewhat did the below and u have to try doing the same with automation
the project compares sectors like aviation, finance, pharma, and technology
it analyzes normalized stock values and correlations
it calculates annualized risk and returns
it evaluates portfolio ROI for different investor types
    -----------------    
what new things to add/show
• API Integration with Python
• Error handling and data validation
• Automating email or PDF report generation
• Develop complex DAX measures for YoY growth and profit margins
• Implement dynamic forecasting using Power BI
• need to show this in skills- GPT-4 (Prompt Engineering) or Strategic Prompt Engineering (maybe to show error handling part or show this to show understanding of errors faced while writing code)
     ---------------
modern elements like:

API mention
try-except improvement
reusable functions
automation angle
AI-assisted optimization
Power BI visualization angle

DATA VALIDATION
“Checking whether data is correct before using it.”
Example:
Suppose API returns:
price = -500
Impossible stock price.
So validation checks:
if price > 0:
    use data
Another example:
API returns empty data.
Validation checks:
if data is not empty:
    continue
    
    
AUTOMATION REPORTS
Every morning:
Python automatically creates:
Portfolio Report
        ----------------
Apple: +5%
Tesla: -2%
Total Return: +12%
Then:
saves PDF
OR
emails report
Automatically.


What I Recommend For YOU
For now:
simulate automation conceptually.
Meaning:
fetch latest data
maybe create auto-generated summary
maybe show refreshed dashboard
                     and thats it!!! you are a data analyst not a data engineer!!!

# Fintech Portfolio Tracker

This project fetches stock market data using Python and prepares data for portfolio analysis and dashboard visualization.

!pip install yfinance  #yfinance is a finance data specific python library that will fetch data from yahoo finance site

In [1]:
import yfinance as yf 
import pandas as pd

In [2]:
ticker = "AAPL"

stock_data = yf.download(ticker, period="5d")

stock_data.head()

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2026-06-01  306.309998  310.940002  305.019989  309.630005  48849900
2026-06-02  315.200012  315.450012  306.690002  307.459991  44534700
2026-06-03  310.260010  316.940002  308.850006  314.179993  50836700
2026-06-04  311.230011  313.540009  309.649994  313.230011  44869100
2026-06-05  307.339996  315.170013  307.149994  312.859985  65246700

In [3]:
stock_dictionary = {
    "Finance": ["JPM", "MS", "GS", "BAC", "C"],
    "Technology": ["AAPL", "MSFT", "AMZN", "GOOG", "NVDA"],
    "Healthcare": ["PFE", "JNJ", "MRK", "UNH", "ABBV"],
    "Automobile": ["TSLA", "F", "GM", "TM", "RIVN","TATAMOTORS.NS"]
}
tickers = []

for stocks in stock_dictionary.values():
    tickers.extend(stocks)

try:
    portfolio_data = yf.download(tickers, period="5d")

except Exception as e:
    print("Download failed")
    print(e)

[**********************76%***********            ]  16 of 21 completedHTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}
$TATAMOTORS.NS: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[*********************100%***********************]  21 of 21 completed

1 Failed download:
['TATAMOTORS.NS']: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

In [4]:
portfolio_data.head(5)

Price          Adj Close       Close                                     \
Ticker     TATAMOTORS.NS        AAPL        ABBV        AMZN        BAC
Date
2026-06-01           NaN  306.309998  212.929993  261.260010  51.243748
2026-06-02           NaN  315.200012  215.399994  256.519989  52.208736
2026-06-03           NaN  310.260010  217.130005  250.020004  52.129150
2026-06-04           NaN  311.230011  224.940002  253.789993  53.889999
2026-06-05           NaN  307.339996  227.229996  246.029999  53.830002

Price                                                                  ...  \
Ticker               C          F         GM        GOOG           GS  ...
Date                                                                   ...
2026-06-01  129.089996  16.629999  82.501167  372.579987  1048.579956  ...
2026-06-02  131.259995  16.150000  81.553230  358.390015  1064.579956  ...
2026-06-03  129.929993  15.710000  81.523285  355.679993  1041.020020  ...
2026-06-04  135.149994  15.340000  83.040001  369.269989  1092.609985  ...
2026-06-05  132.470001  14.900000  82.110001  365.760010  1038.680054  ...

Price         Volume                                                    \
Ticker           MRK       MS      MSFT       NVDA       PFE      RIVN
Date
2026-06-01   9406700  6431200  53628900  212850700  35553600  43483500
2026-06-02   8311500  7664400  37036800  193362900  31295700  39250200
2026-06-03   8225100  5957300  39037000  160907000  30957100  51857200
2026-06-04  15933900  5565300  26899500  169022200  31272000  35162000
2026-06-05  15964600  6169900  34641500  218529000  32159700  35786900

Price
Ticker     TATAMOTORS.NS      TM      TSLA       UNH
Date
2026-06-01           NaN  714700  44937900   6623700
2026-06-02           NaN  922400  37596000   3874400
2026-06-03           NaN  475300  44500700   6808400
2026-06-04           NaN  564300  35323300  12666100
2026-06-05           NaN  750300  63128800  10889000

[5 rows x 106 columns]

In [5]:
# data quality checks
failed_tickers = portfolio_data["Close"].isna().all()
failed_tickers = failed_tickers[failed_tickers]
failed_ticker_list = failed_tickers.index.tolist()
print("Failed tickers:")
print(failed_ticker_list)

Failed tickers:
['TATAMOTORS.NS']

In [6]:
portfolio_data = portfolio_data.drop(
    columns=failed_ticker_list,
    level=1
)

#### Clean dataframe presentation

In [7]:
latest_date = portfolio_data.index[-1]

In [8]:
clean_table = pd.DataFrame({
    "Close": portfolio_data["Close"].loc[latest_date],
    "High": portfolio_data["High"].loc[latest_date],
    "Low": portfolio_data["Low"].loc[latest_date],
    "Open": portfolio_data["Open"].loc[latest_date],
    "Volume": portfolio_data["Volume"].loc[latest_date]
})

In [9]:
clean_table.head()

             Close        High         Low        Open    Volume
Ticker
AAPL    307.339996  315.170013  307.149994  312.859985  65246700
ABBV    227.229996  230.470001  226.000000  227.369995   6246700
AMZN    246.029999  256.380005  245.779999  254.259995  55498100
BAC      53.830002   54.279999   53.320000   54.169998  38822900
C       132.470001  135.830002  131.190002  135.410004  12555800

In [10]:
# need date column as well
clean_table = clean_table.reset_index()

In [11]:
clean_table.head(1)

  Ticker       Close        High         Low        Open    Volume
0   AAPL  307.339996  315.170013  307.149994  312.859985  65246700

In [12]:
# add date column
clean_table["Date"] = latest_date

In [13]:
clean_portfolio_data = clean_table[["Ticker","Date","Close","High","Low","Open","Volume"]]
clean_portfolio_data.head()

  Ticker       Date       Close        High         Low        Open    Volume
0   AAPL 2026-06-05  307.339996  315.170013  307.149994  312.859985  65246700
1   ABBV 2026-06-05  227.229996  230.470001  226.000000  227.369995   6246700
2   AMZN 2026-06-05  246.029999  256.380005  245.779999  254.259995  55498100
3    BAC 2026-06-05   53.830002   54.279999   53.320000   54.169998  38822900
4      C 2026-06-05  132.470001  135.830002  131.190002  135.410004  12555800

In [14]:
ticker_sector = {}

for sector, stocks in stock_dictionary.items():
    for stock in stocks:
        ticker_sector[stock] = sector

In [15]:
clean_portfolio_data["Sector"] = clean_portfolio_data["Ticker"].map(ticker_sector)

C:\Users\Ashlesha\AppData\Local\Temp\ipykernel_35704\1232821456.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_portfolio_data["Sector"] = clean_portfolio_data["Ticker"].map(ticker_sector)

In [16]:
clean_portfolio_data = clean_portfolio_data[["Ticker", "Sector", "Date", "Close", "High","Low", "Open", "Volume"]]

clean_portfolio_data.head()

,Ticker,Sector,Date,Close,High,Low,Open,Volume
0,AAPL,Technology,2026-06-05,307.339996,315.170013,307.149994,312.859985,65246700
1,ABBV,Healthcare,2026-06-05,227.229996,230.470001,226.000000,227.369995,6246700
2,AMZN,Technology,2026-06-05,246.029999,256.380005,245.779999,254.259995,55498100
3,BAC,Finance,2026-06-05,53.830002,54.279999,53.320000,54.169998,38822900
4,C,Finance,2026-06-05,132.470001,135.830002,131.190002,135.410004,12555800